[project]
name = "tex-match"
version = "0.1.0"
description = "Image comparison tool"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "opencv-python>=4.10.0.84",
    "numpy>=2.1.0",
    "imageio>=2.35.1",
    "scikit-image",
]
